version: '3.8'
services:
  postgres:
    container_name: expense_tracker_app_db
    image: postgres:15.2-alpine
    volumes:
      - dbdata:/var/lib/postresql/data
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: expense_tracker

volumes:
  dbdata:
    name: expense_tracker_app_db_volume
