name: run-tests-on-PR
run-name: Run tests on PR from ${{ github.head_ref }} to main by ${{ github.actor }}

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'


    - name: Install dependencies
      run: npm install

    - name: Run end-to-end tests
      run: npm run test:e2e

    - name: Check if tests passed
      if: failure()
      run: exit 1
